<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQfBnUim\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQfBnUim/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerQfBnUim.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerQfBnUim\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerQfBnUim\appAppKernelProdContainer([
    'container.build_hash' => 'QfBnUim',
    'container.build_id' => '1ebed5f3',
    'container.build_time' => 1689039445,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQfBnUim');
